name: RISCV/gem5.opt build CI

on:
  push:
    branches: [ "rvv-cpu" ]
  pull_request:
    branches: [ "rvv-cpu" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential git-core m4 scons zlib1g zlib1g-dev libprotobuf-dev protobuf-compiler libprotoc-dev libgoogle-perftools-dev swig python-dev python
          apt-get clean
      
      - uses: actions/checkout@v3

      - name: RISCV/gem5.opt build
        run: |
          /usr/bin/env python3 $(which scons) build/RISCV/gem5.opt -j32
